# Generated by Django 4.2.7 on 2024-05-11 23:11

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_classroomgroup_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomgroup',
            name='code',
            field=models.CharField(default=base.models.generate_unique_code, editable=False, max_length=8, unique=True),
        ),
    ]
