# Generated by Django 4.2.7 on 2024-05-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_lessonpage_iscontentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='canvaEmbedUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
