# Generated by Django 4.2.7 on 2024-05-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_lessonpage_svg_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='svg_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
