# Generated by Django 5.0.6 on 2024-06-26 17:24

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_tutorialpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_class', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_1_button_text',
            field=models.CharField(default='Learn More', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_1_text',
            field=wagtail.fields.RichTextField(default='Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_1_title',
            field=models.CharField(default='Featured Section 1', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_2_button_text',
            field=models.CharField(default='Explore', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_2_text',
            field=wagtail.fields.RichTextField(default='Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_2_title',
            field=models.CharField(default='Featured Section 2', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='people_searching_text',
            field=models.CharField(default='People are searching:', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='search_placeholder',
            field=models.CharField(default='Search for help...', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='HomePageQuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_links', to='base.homepage')),
                ('quick_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.quicklink')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('term', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_terms', to='base.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
