# Generated by Django 5.0.6 on 2024-06-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_quicklink_remove_homepage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicklink',
            name='icon_class',
            field=models.CharField(help_text="Font Awesome class without 'fa-' prefix. E.g., 'user' for 'fa-user'", max_length=50),
        ),
    ]
