# Generated by Django 5.0.6 on 2024-06-27 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_quicklink_icon_class'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quicklink',
            name='url',
        ),
        migrations.AddField(
            model_name='quicklink',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='quicklink',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
