# Generated by Django 5.0.6 on 2024-06-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_codesnippetpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='fuck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
