# Generated by Django 5.0.6 on 2024-06-27 17:38

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_codesnippethomepage_delete_fuck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialpage',
            old_name='body',
            new_name='introduction',
        ),
        migrations.RemoveField(
            model_name='tutorialpage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='tutorialpage',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='tutorialpage',
            name='content',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock()), ('code', wagtail.blocks.StructBlock([('language', wagtail.blocks.ChoiceBlock(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS')])), ('code', wagtail.blocks.TextBlock())])), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True),
        ),
    ]
