# Generated by Django 5.0.6 on 2024-06-27 17:57

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_tutorialhomepage'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Optional introduction text for the FAQ page')),
                ('faqs', wagtail.fields.StreamField([('faq_item', wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(help_text='Add the question here', required=True)), ('answer', wagtail.blocks.RichTextBlock(help_text='Add the answer here', required=True))]))], help_text='Add FAQ items')),
            ],
            options={
                'verbose_name': 'FAQ Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
