# Generated by Django 5.0.6 on 2024-06-30 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_assignment_studentassignment_studentprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_pages', to='base.lesson'),
        ),
    ]
