# Generated by Django 5.0.6 on 2024-06-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_lessonpage_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
