# Generated by Django 5.0.6 on 2024-06-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_course_category_course_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='Default Description'),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='avatar.svg', upload_to=''),
        ),
    ]
