# Generated by Django 5.0.6 on 2024-07-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_course_description_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_super_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
