# Generated by Django 5.0.6 on 2024-07-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_user_is_super_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='points_worth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
