# Generated by Django 5.0.6 on 2024-07-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_assignment_points_worth'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
