# Generated by Django 5.0.6 on 2024-07-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_studentprogress_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomlesson',
            name='randomfield',
            field=models.BooleanField(default=False),
        ),
    ]
