# Generated by Django 5.0.6 on 2024-07-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_course_author_lesson_author_lessonpage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
