# Generated by Django 5.0.6 on 2024-08-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_classroomannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomannouncement',
            name='announcement_content',
            field=models.TextField(null=True),
        ),
    ]
