# Generated by Django 5.0.6 on 2024-08-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_classroomannouncement_announcement_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomannouncement',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
