# Generated by Django 5.0.6 on 2024-08-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_classroomannouncement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomannouncement',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
