# Generated by Django 5.0.6 on 2024-09-04 22:36

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_classroomannouncement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
