# Generated by Django 5.0.6 on 2024-10-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_lesson_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='category',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
